export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const REGISTER_USER_PASSWORD_MISMATCH =
  "REGISTER_USER_PASSWORD_MISMATCH";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_OFFERS_BEGIN = "GET_OFFER_BEGIN";
export const GET_OFFERS_SUCCESS = "GET_OFFER_SUCCESS";
export const GET_OFFERS_ERROR = "GET_OFFER_ERROR";

export const POST_OFFER_BEGIN = "POST_OFFER_BEGIN";
export const POST_OFFER_SUCCESS = "POST_OFFER_SUCCESS";
export const POST_OFFER_ERROR = "POST_OFFER_ERROR";

export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
